# Generated by Django 4.0 on 2021-12-18 11:55

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='subject',
            field=models.CharField(max_length=50, verbose_name='Ödevin Konusu'),
        ),
    ]
