# Generated by Django 4.0 on 2021-12-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_alter_pdf_content_alter_pdf_date_alter_pdf_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='', verbose_name='Ödev Dosyası'),
        ),
    ]
